#!/usr/bin/env bash
mpm install
mpm build --input "src/tag-util" --output "test/TagUtil.cs"
mpm build --input "src/text-size-util" --output "test/TextSizeUtil.cs"
mpm build --input "src/tag-service" --output "test/TagService.cs"
mpm build --input "src/step-service" --output "test/StepService.cs"
mpm build --input "src/signal" --output "test/Signal.cs"
mpm build --input "src/quad-tree" --output "test/QuadTree.cs"
mpm build --input "src/player-util" --output "test/PlayerUtil.cs"
mpm build --input "src/option" --output "test/Option.cs"
mpm build --input "src/maid" --output "test/Maid.cs"
mpm build --input "src/coordinate-service" --output "test/CoordinateService.cs"
mpm build --input "src/task-util" --output "test/TaskUtil.cs"
mpm build --input "src/attribute-util" --output "test/AttributeUtil.cs"
mpm build --input "src/bit32-util" --output "test/Bit32Util.cs"
mpm build --input "src/data-service" --output "test/DataService.cs"
mpm build --input "src/attribute-service" --output "test/AttributeService.cs"
mpm build --input "src/test-service" --output "test/TestService.cs"